# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn -B test --file pom.xml

    - name: Generate Jacoco Report
      run: mvn jacoco:report

    - name: Upload Jacoco Report
      uses: actions/upload-artifact@v2
      with:
        with:
        name: code-coverage-report
        path: |
              ${{ github.workspace }}/**/build/reports/jacoco/test/html/*
              ${{ github.workspace }}/**/target/site/jacoco/*
              - name: Add Code Coverage to PR
                id: jacoco
                uses: madrapps/jacoco-report@1.6.1
                with:
                  paths: |
                    ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
                    ${{ github.workspace }}/**/target/site/jacoco/jacoco.xml
                  token: ${{ secrets.GITHUB_TOKEN }}
                  title: Code Coverage
                  min-coverage-overall: ${{ inputs.overall-coverage-value }}
                  min-coverage-changed-files: ${{ inputs.changed-files-coverage-value }}
                  pass-emoji: ':green_circle:'
                  fail-emoji: ':red_circle:'
              - name: Fail PR if overall coverage is less than ${{ inputs.overall-coverage-value }}%
                if: ${{ inputs.overall-coverage-flag && steps.jacoco.outputs.coverage-overall < inputs.overall-coverage-value }}
                uses: actions/github-script@v7.0.1
                with:
                  script: |
                    core.setFailed('Overall coverage is less than ${{ inputs.overall-coverage-value }}%!')
              - name: Fail PR if changed files coverage is less than ${{ inputs.changed-files-coverage-value }}%
                if: ${{ steps.jacoco.outputs.coverage-changed-files < inputs.changed-files-coverage-value }}
                uses: actions/github-script@v7.0.1
                with:
                  script: |
                    core.setFailed('Changed files coverage is less than ${{ inputs.changed-files-coverage-value }}%!')
